@startuml
'https://plantuml.com/class-diagram


entity Player

Player *-- AnimationComponent
Player *-- TextureComponent

class TextureComponent {
Texture texture
}

class AnimationComponent {
 int direction
 int cycle
 Texture[][] animationMap
 boolean isWalking
}





@enduml