@startuml
'https://plantuml.com/class-diagram

entity Player

Player *-- PositionComponent
Player *-- TextureComponent
Player *-- VelocityComponent

class TextureComponent {
Texture texture
}

class VelocityComponent {
float x
float y
}

class PositionComponent {
float x
float y
int z
}


@enduml