@startuml
'https://plantuml.com/sequence-diagram

autonumber

MovementSystem -> AnimationSystem: Update player sprite for movement
MovementSystem -> RenderSystem: Update player position
AnimationSystem -> RenderSystem: Draw new player sprite

@enduml