@startuml

package "Systems" {
    [RenderSystem]
    [AnimationSystem]
    [MovementSystem]
}

[RenderSystem]

[AnimationComponent] -> [Player]
[Player] <-- [VelocityComponent]
[TextureComponent] --> [Player]
[Player] <- [PositionComponent]

@enduml